### ISSUE TITLE
tags are gone after using gitrewrite

### ISSUE THREAD

**Issue by fobrs** [TimHeinrich/GitRewrite#2]
Hi,

I've used gitrewrite to remove a large file from a git repository.
But now, when I open the log with TortoiseGit I get:

"Could not get all refs.
libgit2 returned: failed to parse tag: tag contains no message"

Then it shows  the log without the tags

It turns out a few tags had their messages removed....

**Comment by fobrs** [comment]
I think this has to do with the difference between 'Annotated tags' and 'lightweight tags'.
Because the _type contains "type commit" and not "type tag" or "type tree".

I changed you code at line 139 of Refs.cs like this:

` if (tag.PointsToTree || tag.PointsToCommit)
                {
                    // Do not touch tags pointing to trees right now as this is not properly implemented yet
                    return tag.Hash;
                }
`

**Comment by TimHeinrich** [comment]
Thanks for reporting this issue, I will have another look at tags later today. Do you have a repository I can use for my tests with which I can reproduce this? And which version did you use, latest from master or latest release?

**Comment by fobrs** [comment]
Hi I use latest from master. I've found the bug. Please forget my previous change ...

You need to add at line 91 of Tag.cs:

  resultBuffer[resultIndex++] = 10;
 
Then it works ok fro me!

**Comment by fobrs** [comment]
Sorry, I cannot give you my test repo, as that contains copyrighted code.

But you can easily reproduce by adding an annotated 'tag'. Then GitRewrite needs to rewrite the object and appends the tag message to the tagger string....

**Comment by TimHeinrich** [comment]
Thanks, this should be fixed with 72e92f9a095f2afb7a2588b23d6e48500208ba4f
