### ISSUE TITLE
Contributor is spelled incorrectly throughout the program

### ISSUE THREAD

**Issue by twwilliams** [TimHeinrich/GitRewrite#5]
It is spelled Contributer instead of Contributor.

I would be willing to fix this and submit a pull request if you're interested.

**Comment by TimHeinrich** [comment]
Thanks for submitting the issue! It will be corrected faster if you submit a pull request, otherwise I will fix this the next time I get to code in my free time.

**Comment by twwilliams** [comment]
OK. Sure thing. I'll work on it this weekend.

**Comment by twwilliams** [comment]
Just submitted a pull request for this one: #6
