### ISSUE TITLE
Crash when contributers.txt has empty lines

### ISSUE THREAD

**Issue by ktzanev** [TimHeinrich/GitRewrite#9]
Everything is in the title. When using 
```
> GitRewrite.exe --contributer-names .git > contributers.txt
```
with file `contributers.txt` that contains empty lines (in my case three at the end of the file) it craches.

**Comment by TimHeinrich** [comment]
Hi, can you give a little more detail on when the crash occurs and what the error is? Because the command you stated does not read the text-file at all and the "> contributers.txt" has nothing to do with GitRewrite...
So basically: 
- What is the exact command where the error occurs 
- What is the error message

**Comment by TimHeinrich** [comment]
Assuming you mean not creating the contributors.txt but using it, then you might want to try the code in branch issue/9, which might fix your problem.

**Comment by TimHeinrich** [comment]
Should fix your problem, if it does not please reopen the issue

**Comment by ktzanev** [comment]
Thanks for considering my request. I haven't checked yet if it is ok now, but I can give you more details. There was an exception `"Mapping is not formatted properly."` due to empty lines in the file. So I suppose the corresponding code was from [line 21 of RewriteContributorTask.cs](https://github.com/TimHeinrich/GitRewrite/blob/3e1062406a2e4ca1472c81688631d1eedeab1161/GitRewrite/CleanupTask/RewriteContributorTask.cs#L21).

**Comment by ktzanev** [comment]
I wanted to test the new version, but I was not able to do it. The following command crashes:
```powershell
> GitRewrite.exe .\temp\.git\ --rewrite-contributers .\contributers.txt
Unhandled exception. System.ArgumentException: Could not parse arguments.
   at GitRewrite.CommandLineOptions.TryParse(String[] args, CommandLineOptions& options)
   at GitRewrite.Program.Main(String[] args)
```

I checked in powershell and in gitbash, same result.

**Comment by TimHeinrich** [comment]
Ah yes, see #5, the parameter must be --rewrite-contribut**o**rs now, this was a typo before

**Comment by ktzanev** [comment]
Well it works now, with empty lines and with `contributors` ;)
